name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip downloads
      uses: syphar/restore-pip-download-cache@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions codecov
        pip install -r requirements-dev.txt

    - name: Test with tox
      run: python -m tox

    - name: installing coveragepy for codecov upload
      # the codecov github action needs this package to find the reports
      run: pip install coverage

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
